version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Aitodo816*
      - MYSQL_DB=aitodo
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Aitodo816*
      - MYSQL_DATABASE=aitodo
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/sqlScript/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "3306:3306"

volumes:
  db_data: